### ISSUE TITLE
Add Internationalization (i18n)

### ISSUE THREAD

**Issue by vishal-neochrome** [kissplugins/KISS-contactus-shortcode#1]
- Use the __() and _e() functions for all strings

e.g. __('Contact Us', 'kiss-contactus-shortcode');

**Comment by kissplugins** [comment]
@vishal-neochrome please see and process PR for this:
https://github.com/kissplugins/KISS-contactus-shortcode/pull/3

**Comment by vishal-neochrome** [comment]
Its Done
